networks:
  dev:

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - dev
    expose:
      - 8000
    restart: always
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - dev
    depends_on:
      - backend
    restart: always